--Ex1
SELECT
SUM (CASE WHEN DEVICE_TYPE = 'LAPTOP' THEN 1 ELSE 0 END) AS LAPTOP_VIEWS,
SUM (CASE WHEN DEVICE_TYPE IN ('TABLET','PHONE') THEN 1 ELSE 0 END) AS MOBILE_VIEWS
FROM VIEWERSHIP

--Ex2
SELECT x, y, z,
CASE
    WHEN x + y > z AND x + z > y AND y + z > x THEN 'Yes'
    ELSE 'No'
END AS TRIANGLE
FROM TRIANGLE

--Ex3
SELECT 
ROUND(COUNT(CASE WHEN CALL_CATEGORY = 'N/A' OR CALL_CATEGORY = 'NULL' THEN 1 END) * 100.0 / COUNT(*), 1) AS UNCATEGORISED_CALL_PCT
FROM CALLERS
  
--Ex4
SELECT NAME FROM CUSTOMER
WHERE REFEREE_ID <> 2 OR REFEREE_ID IS NULL

--Ex5
SELECT SURVIVED,
SUM (CASE WHEN PCLASS = 1 THEN 1 ELSE 0 END) AS FIRST_CLASS,
SUM (CASE WHEN PCLASS = 2 THEN 1 ELSE 0 END) AS SECOND_CLASS,
SUM (CASE WHEN PCLASS = 3 THEN 1 ELSE 0 END) AS THIRD_CLASS
FROM TITANIC
GROUP BY SURVIVED
